server:
    port: 1500
    servlet:
        context-path: /caption-assistant

spring:
    datasource:
        url: jdbc:mysql://localhost/caption-assistant
        username: root
        password: Root

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    secret_key: FsNsAOUrBBNQ9HV0QOLm2xhAkdUXwMHhbyMyARzPr6B

ollama:
    api:
        url: http://localhost:11434/api/generate
        model: qwen2.5:3b
